require('dotenv').config();


const fakeRequest = require('supertest');
const app = require('../lib/app');
// const client = require('../lib/client');

describe('app routes', () => {
  describe('routes', () => {
  
    test('returns locations', async() => {


      const expectation = {
        'formatted_query': 'Seattle, King County, Washington, USA',
        'latitude': '47.6038321',
        'longitude': '-122.3300624',
      };

      const data = await fakeRequest(app)
        .get('/location?search=seattle')
        .expect('Content-Type', /json/)
        .expect(200);

      expect(data.body).toEqual(expectation);
    });

    //   test('returns weather data', async () => {


    //       const expectation = {
    //           'forecast': 'Partly cloudy until afternoon.',
    //           'time': 'Tuesday, June 29, 2021'
    //       },
    //           {
    //               'forecast': 'Mostly cloudy in the morning.',
    //               'time': 'Wednesday, June 30, 2021'
    //   };

    //       const input {
    //         'data': [
    //               {
    //                   "moonrise_ts": 1624578299,
    //                   "wind_cdir": "NE",
    //                   "rh": 54,
    //                   "pres": 1014.53,
    //                   "high_temp": 26.1,
    //                   "sunset_ts": 1624581292,
    //                   "ozone": 331.452,
    //                   "moon_phase": 0.992852,
    //                   "wind_gust_spd": 8.29688,
    //                   "snow_depth": 0,
    //                   "clouds": 1,
    //                   "ts": 1624507260,
    //                   "sunrise_ts": 1624528690,
    //                   "app_min_temp": 17.1,
    //                   "wind_spd": 3.24218,
    //                   "pop": 0,
    //                   "wind_cdir_full": "northeast",
    //                   "slp": 1024.41,
    //                   "moon_phase_lunation": 0.49,
    //                   "valid_date": "2021-06-24",
    //                   "app_max_temp": 25.8,
    //                   "vis": 24.096,
    //                   "dewpt": 13.1,
    //                   "snow": 0,
    //                   "uv": 1.73357,
    //                   "weather": {
    //                       "icon": "c02d",
    //                       "code": 801,
    //                       "description": "Few clouds"
    //                   },
    //                   "wind_dir": 47,
    //                   "max_dhi": null,
    //                   "clouds_hi": 0,
    //                   "precip": 0,
    //                   "low_temp": 17.4,
    //                   "max_temp": 26.1,
    //                   "moonset_ts": 1624530945,
    //                   "datetime": "2021-06-24",
    //                   "temp": 23.4,
    //                   "min_temp": 15.6,
    //                   "clouds_mid": 0,
    //                   "clouds_low": 1
    //               },
    //               {
    //                   "moonrise_ts": 1624668902,
    //                   "wind_cdir": "E",
    //                   "rh": 83,
    //                   "pres": 1012.9,
    //                   "high_temp": 26.8,
    //                   "sunset_ts": 1624667698,
    //                   "ozone": 312.323,
    //                   "moon_phase": 0.957461,
    //                   "wind_gust_spd": 8.89844,
    //                   "snow_depth": 0,
    //                   "clouds": 50,
    //                   "ts": 1624593660,
    //                   "sunrise_ts": 1624615109,
    //                   "app_min_temp": 17.4,
    //                   "wind_spd": 1.90821,
    //                   "pop": 75,
    //                   "wind_cdir_full": "east",
    //                   "slp": 1022.92,
    //                   "moon_phase_lunation": 0.53,
    //                   "valid_date": "2021-06-25",
    //                   "app_max_temp": 28.2,
    //                   "vis": 22.5667,
    //                   "dewpt": 18,
    //                   "snow": 0,
    //                   "uv": 5.9769,
    //                   "weather": {
    //                       "icon": "t02d",
    //                       "code": 201,
    //                       "description": "Thunderstorm with rain"
    //                   },
    //                   "wind_dir": 99,
    //                   "max_dhi": null,
    //                   "clouds_hi": 12,
    //                   "precip": 8.3125,
    //                   "low_temp": 18.3,
    //                   "max_temp": 26.9,
    //                   "moonset_ts": 1624621431,
    //                   "datetime": "2021-06-25",
    //                   "temp": 21.2,
    //                   "min_temp": 17.4,
    //                   "clouds_mid": 4,
    //                   "clouds_low": 48
    //               },
    //               {
    //                   "moonrise_ts": 1624758992,
    //                   "wind_cdir": "SE",
    //                   "rh": 85,
    //                   "pres": 1012.19,
    //                   "high_temp": 29.1,
    //                   "sunset_ts": 1624754102,
    //                   "ozone": 297.438,
    //                   "moon_phase": 0.896015,
    //                   "wind_gust_spd": 7.89844,
    //                   "snow_depth": 0,
    //                   "clouds": 79,
    //                   "ts": 1624680060,
    //                   "sunrise_ts": 1624701528,
    //                   "app_min_temp": 22.6,
    //                   "wind_spd": 2.48349,
    //                   "pop": 55,
    //                   "wind_cdir_full": "southeast",
    //                   "slp": 1022.15,
    //                   "moon_phase_lunation": 0.56,
    //                   "valid_date": "2021-06-26",
    //                   "app_max_temp": 32.5,
    //                   "vis": 23.5917,
    //                   "dewpt": 21.9,
    //                   "snow": 0,
    //                   "uv": 6.26426,
    //                   "weather": {
    //                       "icon": "c04d",
    //                       "code": 804,
    //                       "description": "Overcast clouds"
    //                   },
    //                   "wind_dir": 130,
    //                   "max_dhi": null,
    //                   "clouds_hi": 23,
    //                   "precip": 3.5625,
    //                   "low_temp": 22.5,
    //                   "max_temp": 29.9,
    //                   "moonset_ts": 1624712028,
    //                   "datetime": "2021-06-26",
    //                   "temp": 24.8,
    //                   "min_temp": 21.8,
    //                   "clouds_mid": 7,
    //                   "clouds_low": 65
    //               },
    //               {
    //                   "moonrise_ts": 1624848473,
    //                   "wind_cdir": "SSE",
    //                   "rh": 71,
    //                   "pres": 1007.52,
    //                   "high_temp": 32.6,
    //                   "sunset_ts": 1624840504,
    //                   "ozone": 297.01,
    //                   "moon_phase": 0.814811,
    //                   "wind_gust_spd": 8.00781,
    //                   "snow_depth": 0,
    //                   "clouds": 52,
    //                   "ts": 1624766460,
    //                   "sunrise_ts": 1624787950,
    //                   "app_min_temp": 21.7,
    //                   "wind_spd": 2.73777,
    //                   "pop": 25,
    //                   "wind_cdir_full": "south-southeast",
    //                   "slp": 1021.17,
    //                   "moon_phase_lunation": 0.59,
    //                   "valid_date": "2021-06-27",
    //                   "app_max_temp": 33.3,
    //                   "vis": 23.7153,
    //                   "dewpt": 19.9,
    //                   "snow": 0,
    //                   "uv": 9.77943,
    //                   "weather": {
    //                       "icon": "c03d",
    //                       "code": 803,
    //                       "description": "Broken clouds"
    //                   },
    //                   "wind_dir": 163,
    //                   "max_dhi": null,
    //                   "clouds_hi": 34,
    //                   "precip": 1.125,
    //                   "low_temp": 20.9,
    //                   "max_temp": 32.8,
    //                   "moonset_ts": 1624802531,
    //                   "datetime": "2021-06-27",
    //                   "temp": 26.2,
    //                   "min_temp": 20.9,
    //                   "clouds_mid": 33,
    //                   "clouds_low": 10
    //               },
    //               {
    //                   "moonrise_ts": 1624937401,
    //                   "wind_cdir": "SSE",
    //                   "rh": 64,
    //                   "pres": 1009.12,
    //                   "high_temp": 32.9,
    //                   "sunset_ts": 1624926905,
    //                   "ozone": 308.458,
    //                   "moon_phase": 0.72059,
    //                   "wind_gust_spd": 9.5,
    //                   "snow_depth": 0,
    //                   "clouds": 17,
    //                   "ts": 1624852860,
    //                   "sunrise_ts": 1624874372,
    //                   "app_min_temp": 21.5,
    //                   "wind_spd": 2.64658,
    //                   "pop": 0,
    //                   "wind_cdir_full": "south-southeast",
    //                   "slp": 1022.69,
    //                   "moon_phase_lunation": 0.63,
    //                   "valid_date": "2021-06-28",
    //                   "app_max_temp": 33.2,
    //                   "vis": 24.128,
    //                   "dewpt": 18.7,
    //                   "snow": 0,
    //                   "uv": 10.7822,
    //                   "weather": {
    //                       "icon": "c02d",
    //                       "code": 801,
    //                       "description": "Few clouds"
    //                   },
    //                   "wind_dir": 158,
    //                   "max_dhi": null,
    //                   "clouds_hi": 13,
    //                   "precip": 0,
    //                   "low_temp": 21.4,
    //                   "max_temp": 33,
    //                   "moonset_ts": 1624892840,
    //                   "datetime": "2021-06-28",
    //                   "temp": 26.9,
    //                   "min_temp": 20.9,
    //                   "clouds_mid": 6,
    //                   "clouds_low": 2
    //               },
    //               {
    //                   "moonrise_ts": 1624939500,
    //                   "wind_cdir": "SSE",
    //                   "rh": 69,
    //                   "pres": 1009.45,
    //                   "high_temp": 32.3,
    //                   "sunset_ts": 1625013305,
    //                   "ozone": 322.7,
    //                   "moon_phase": 0.619469,
    //                   "wind_gust_spd": 9,
    //                   "snow_depth": 0,
    //                   "clouds": 40,
    //                   "ts": 1624939260,
    //                   "sunrise_ts": 1624960796,
    //                   "app_min_temp": 22,
    //                   "wind_spd": 2.58433,
    //                   "pop": 20,
    //                   "wind_cdir_full": "south-southeast",
    //                   "slp": 1022.95,
    //                   "moon_phase_lunation": 0.66,
    //                   "valid_date": "2021-06-29",
    //                   "app_max_temp": 32.8,
    //                   "vis": 24.128,
    //                   "dewpt": 19.5,
    //                   "snow": 0,
    //                   "uv": 6.22353,
    //                   "weather": {
    //                       "icon": "c02d",
    //                       "code": 802,
    //                       "description": "Scattered clouds"
    //                   },
    //                   "wind_dir": 160,
    //                   "max_dhi": null,
    //                   "clouds_hi": 24,
    //                   "precip": 0.1875,
    //                   "low_temp": 21.6,
    //                   "max_temp": 32.6,
    //                   "moonset_ts": 1624982946,
    //                   "datetime": "2021-06-29",
    //                   "temp": 26.1,
    //                   "min_temp": 21.2,
    //                   "clouds_mid": 0,
    //                   "clouds_low": 28
    //               },
    //               {
    //                   "moonrise_ts": 1625027702,
    //                   "wind_cdir": "S",
    //                   "rh": 70,
    //                   "pres": 1005.94,
    //                   "high_temp": 29.3,
    //                   "sunset_ts": 1625099702,
    //                   "ozone": 313.688,
    //                   "moon_phase": 0.516466,
    //                   "wind_gust_spd": 7.40234,
    //                   "snow_depth": 0,
    //                   "clouds": 74,
    //                   "ts": 1625025660,
    //                   "sunrise_ts": 1625047221,
    //                   "app_min_temp": 22.3,
    //                   "wind_spd": 2.59798,
    //                   "pop": 20,
    //                   "wind_cdir_full": "south",
    //                   "slp": 1019.38,
    //                   "moon_phase_lunation": 0.69,
    //                   "valid_date": "2021-06-30",
    //                   "app_max_temp": 33.1,
    //                   "vis": 24.128,
    //                   "dewpt": 19.9,
    //                   "snow": 0,
    //                   "uv": 3.25721,
    //                   "weather": {
    //                       "icon": "c04d",
    //                       "code": 804,
    //                       "description": "Overcast clouds"
    //                   },
    //                   "wind_dir": 186,
    //                   "max_dhi": null,
    //                   "clouds_hi": 74,
    //                   "precip": 0.0625,
    //                   "low_temp": 22.6,
    //                   "max_temp": 32.8,
    //                   "moonset_ts": 1625072892,
    //                   "datetime": "2021-06-30",
    //                   "temp": 26.3,
    //                   "min_temp": 21.3,
    //                   "clouds_mid": 12,
    //                   "clouds_low": 16
    //               },
    //               {
    //                   "moonrise_ts": 1625115718,
    //                   "wind_cdir": "S",
    //                   "rh": 77,
    //                   "pres": 1004.06,
    //                   "high_temp": 28.1,
    //                   "sunset_ts": 1625186098,
    //                   "ozone": 306.594,
    //                   "moon_phase": 0.415524,
    //                   "wind_gust_spd": 10.2969,
    //                   "snow_depth": 0,
    //                   "clouds": 87,
    //                   "ts": 1625112060,
    //                   "sunrise_ts": 1625133647,
    //                   "app_min_temp": 23.2,
    //                   "wind_spd": 3.55493,
    //                   "pop": 25,
    //                   "wind_cdir_full": "south",
    //                   "slp": 1017.62,
    //                   "moon_phase_lunation": 0.73,
    //                   "valid_date": "2021-07-01",
    //                   "app_max_temp": 31.4,
    //                   "vis": 23.282,
    //                   "dewpt": 20.3,
    //                   "snow": 0,
    //                   "uv": 5.11324,
    //                   "weather": {
    //                       "icon": "c04d",
    //                       "code": 804,
    //                       "description": "Overcast clouds"
    //                   },
    //                   "wind_dir": 178,
    //                   "max_dhi": null,
    //                   "clouds_hi": 75,
    //                   "precip": 1,
    //                   "low_temp": 21.3,
    //                   "max_temp": 29.6,
    //                   "moonset_ts": 1625162741,
    //                   "datetime": "2021-07-01",
    //                   "temp": 25,
    //                   "min_temp": 21.9,
    //                   "clouds_mid": 53,
    //                   "clouds_low": 30
    //               },
    //               {
    //                   "moonrise_ts": 1625203641,
    //                   "wind_cdir": "S",
    //                   "rh": 84,
    //                   "pres": 1004.56,
    //                   "high_temp": 34.5,
    //                   "sunset_ts": 1625272492,
    //                   "ozone": 304.312,
    //                   "moon_phase": 0.319771,
    //                   "wind_gust_spd": 10.1016,
    //                   "snow_depth": 0,
    //                   "clouds": 78,
    //                   "ts": 1625198460,
    //                   "sunrise_ts": 1625220075,
    //                   "app_min_temp": 22,
    //                   "wind_spd": 3.16827,
    //                   "pop": 75,
    //                   "wind_cdir_full": "south",
    //                   "slp": 1018.12,
    //                   "moon_phase_lunation": 0.76,
    //                   "valid_date": "2021-07-02",
    //                   "app_max_temp": 31.6,
    //                   "vis": 20.48,
    //                   "dewpt": 21.8,
    //                   "snow": 0,
    //                   "uv": 3.26962,
    //                   "weather": {
    //                       "icon": "t02d",
    //                       "code": 201,
    //                       "description": "Thunderstorm with rain"
    //                   },
    //                   "wind_dir": 186,
    //                   "max_dhi": null,
    //                   "clouds_hi": 70,
    //                   "precip": 10.25,
    //                   "low_temp": 21.8,
    //                   "max_temp": 28.5,
    //                   "moonset_ts": 1625252553,
    //                   "datetime": "2021-07-02",
    //                   "temp": 24.7,
    //                   "min_temp": 21.2,
    //                   "clouds_mid": 15,
    //                   "clouds_low": 23
    //               },
    //               {
    //                   "moonrise_ts": 1625291549,
    //                   "wind_cdir": "SSW",
    //                   "rh": 71,
    //                   "pres": 1003.69,
    //                   "high_temp": 35.2,
    //                   "sunset_ts": 1625358885,
    //                   "ozone": 302.531,
    //                   "moon_phase": 0.231902,
    //                   "wind_gust_spd": 11.2969,
    //                   "snow_depth": 0,
    //                   "clouds": 60,
    //                   "ts": 1625284860,
    //                   "sunrise_ts": 1625306504,
    //                   "app_min_temp": 22.6,
    //                   "wind_spd": 3.63114,
    //                   "pop": 55,
    //                   "wind_cdir_full": "south-southwest",
    //                   "slp": 1017.12,
    //                   "moon_phase_lunation": 0.8,
    //                   "valid_date": "2021-07-03",
    //                   "app_max_temp": 36.9,
    //                   "vis": 22.317,
    //                   "dewpt": 21.1,
    //                   "snow": 0,
    //                   "uv": 7.04151,
    //                   "weather": {
    //                       "icon": "c03d",
    //                       "code": 803,
    //                       "description": "Broken clouds"
    //                   },
    //                   "wind_dir": 204,
    //                   "max_dhi": null,
    //                   "clouds_hi": 26,
    //                   "precip": 3.6875,
    //                   "low_temp": 24.1,
    //                   "max_temp": 35.1,
    //                   "moonset_ts": 1625342377,
    //                   "datetime": "2021-07-03",
    //                   "temp": 27.4,
    //                   "min_temp": 21.6,
    //                   "clouds_mid": 4,
    //                   "clouds_low": 43
    //               },
    //               {
    //                   "moonrise_ts": 1625379516,
    //                   "wind_cdir": "SSW",
    //                   "rh": 63,
    //                   "pres": 1002.75,
    //                   "high_temp": 31.5,
    //                   "sunset_ts": 1625445275,
    //                   "ozone": 297.375,
    //                   "moon_phase": 0.154485,
    //                   "wind_gust_spd": 11,
    //                   "snow_depth": 0,
    //                   "clouds": 70,
    //                   "ts": 1625371260,
    //                   "sunrise_ts": 1625392933,
    //                   "app_min_temp": 24.8,
    //                   "wind_spd": 3.71396,
    //                   "pop": 10,
    //                   "wind_cdir_full": "south-southwest",
    //                   "slp": 1016.25,
    //                   "moon_phase_lunation": 0.83,
    //                   "valid_date": "2021-07-04",
    //                   "app_max_temp": 36.7,
    //                   "vis": 24.128,
    //                   "dewpt": 20.4,
    //                   "snow": 0,
    //                   "uv": 4.27858,
    //                   "weather": {
    //                       "icon": "c04d",
    //                       "code": 804,
    //                       "description": "Overcast clouds"
    //                   },
    //                   "wind_dir": 195,
    //                   "max_dhi": null,
    //                   "clouds_hi": 70,
    //                   "precip": 0.375,
    //                   "low_temp": 22.7,
    //                   "max_temp": 34.6,
    //                   "moonset_ts": 1625432237,
    //                   "datetime": "2021-07-04",
    //                   "temp": 29.4,
    //                   "min_temp": 24.1,
    //                   "clouds_mid": 3,
    //                   "clouds_low": 32
    //               },
    //               {
    //                   "moonrise_ts": 1625467615,
    //                   "wind_cdir": "SSW",
    //                   "rh": 58,
    //                   "pres": 1001.25,
    //                   "high_temp": 25.3,
    //                   "sunset_ts": 1625531664,
    //                   "ozone": 300.375,
    //                   "moon_phase": 0.0901316,
    //                   "wind_gust_spd": 8.5,
    //                   "snow_depth": 0,
    //                   "clouds": 92,
    //                   "ts": 1625457660,
    //                   "sunrise_ts": 1625479364,
    //                   "app_min_temp": 26.2,
    //                   "wind_spd": 3.42122,
    //                   "pop": 0,
    //                   "wind_cdir_full": "south-southwest",
    //                   "slp": 1014.5,
    //                   "moon_phase_lunation": 0.86,
    //                   "valid_date": "2021-07-05",
    //                   "app_max_temp": 36.8,
    //                   "vis": 24.128,
    //                   "dewpt": 20.3,
    //                   "snow": 0,
    //                   "uv": 4.41245,
    //                   "weather": {
    //                       "icon": "c04d",
    //                       "code": 804,
    //                       "description": "Overcast clouds"
    //                   },
    //                   "wind_dir": 195,
    //                   "max_dhi": null,
    //                   "clouds_hi": 47,
    //                   "precip": 0,
    //                   "low_temp": 24.2,
    //                   "max_temp": 34.5,
    //                   "moonset_ts": 1625522123,
    //                   "datetime": "2021-07-05",
    //                   "temp": 30.1,
    //                   "min_temp": 25,
    //                   "clouds_mid": 2,
    //                   "clouds_low": 55
    //               },
    //               {
    //                   "moonrise_ts": 1625555921,
    //                   "wind_cdir": "S",
    //                   "rh": 62,
    //                   "pres": 1002,
    //                   "high_temp": 34.6,
    //                   "sunset_ts": 1625618051,
    //                   "ozone": 299.375,
    //                   "moon_phase": 0.0414887,
    //                   "wind_gust_spd": 8.59375,
    //                   "snow_depth": 0,
    //                   "clouds": 75,
    //                   "ts": 1625544060,
    //                   "sunrise_ts": 1625565796,
    //                   "app_min_temp": 25.8,
    //                   "wind_spd": 3.59699,
    //                   "pop": 20,
    //                   "wind_cdir_full": "south",
    //                   "slp": 1015.25,
    //                   "moon_phase_lunation": 0.9,
    //                   "valid_date": "2021-07-06",
    //                   "app_max_temp": 37.8,
    //                   "vis": 24.12,
    //                   "dewpt": 20.9,
    //                   "snow": 0,
    //                   "uv": 3.531,
    //                   "weather": {
    //                       "icon": "c04d",
    //                       "code": 804,
    //                       "description": "Overcast clouds"
    //                   },
    //                   "wind_dir": 191,
    //                   "max_dhi": null,
    //                   "clouds_hi": 29,
    //                   "precip": 0.125,
    //                   "low_temp": 25,
    //                   "max_temp": 35.2,
    //                   "moonset_ts": 1625611979,
    //                   "datetime": "2021-07-06",
    //                   "temp": 30.1,
    //                   "min_temp": 24.2,
    //                   "clouds_mid": 0,
    //                   "clouds_low": 49
    //               },
    //               {
    //                   "moonrise_ts": 1625644514,
    //                   "wind_cdir": "W",
    //                   "rh": 67,
    //                   "pres": 1004,
    //                   "high_temp": 31.4,
    //                   "sunset_ts": 1625704437,
    //                   "ozone": 306.875,
    //                   "moon_phase": 0.0110254,
    //                   "wind_gust_spd": 7.41016,
    //                   "snow_depth": 0,
    //                   "clouds": 52,
    //                   "ts": 1625630460,
    //                   "sunrise_ts": 1625652230,
    //                   "app_min_temp": 24.9,
    //                   "wind_spd": 2.66716,
    //                   "pop": 10,
    //                   "wind_cdir_full": "west",
    //                   "slp": 1017.5,
    //                   "moon_phase_lunation": 0.93,
    //                   "valid_date": "2021-07-07",
    //                   "app_max_temp": 33.5,
    //                   "vis": 24.128,
    //                   "dewpt": 20.5,
    //                   "snow": 0,
    //                   "uv": 3.24697,
    //                   "weather": {
    //                       "icon": "c03d",
    //                       "code": 803,
    //                       "description": "Broken clouds"
    //                   },
    //                   "wind_dir": 260,
    //                   "max_dhi": null,
    //                   "clouds_hi": 52,
    //                   "precip": 0.3125,
    //                   "low_temp": 22.5,
    //                   "max_temp": 31.5,
    //                   "moonset_ts": 1625701713,
    //                   "datetime": "2021-07-07",
    //                   "temp": 27.8,
    //                   "min_temp": 22.5,
    //                   "clouds_mid": 50,
    //                   "clouds_low": 0
    //               },
    //               {
    //                   "moonrise_ts": 1625733460,
    //                   "wind_cdir": "W",
    //                   "rh": 78,
    //                   "pres": 1006.5,
    //                   "high_temp": 28.2,
    //                   "sunset_ts": 1625790821,
    //                   "ozone": 307.75,
    //                   "moon_phase": 0.000721845,
    //                   "wind_gust_spd": 4.51172,
    //                   "snow_depth": 0,
    //                   "clouds": 100,
    //                   "ts": 1625716860,
    //                   "sunrise_ts": 1625738664,
    //                   "app_min_temp": 23.3,
    //                   "wind_spd": 1.43676,
    //                   "pop": 0,
    //                   "wind_cdir_full": "west",
    //                   "slp": 1020.25,
    //                   "moon_phase_lunation": 0.96,
    //                   "valid_date": "2021-07-08",
    //                   "app_max_temp": 25.7,
    //                   "vis": 24.128,
    //                   "dewpt": 19.8,
    //                   "snow": 0,
    //                   "uv": 3.24412,
    //                   "weather": {
    //                       "icon": "c04d",
    //                       "code": 804,
    //                       "description": "Overcast clouds"
    //                   },
    //                   "wind_dir": 279,
    //                   "max_dhi": null,
    //                   "clouds_hi": 79,
    //                   "precip": 0,
    //                   "low_temp": 24.1,
    //                   "max_temp": 28.2,
    //                   "moonset_ts": 1625791219,
    //                   "datetime": "2021-07-08",
    //                   "temp": 24,
    //                   "min_temp": 22.7,
    //                   "clouds_mid": 100,
    //                   "clouds_low": 9
    //               },
    //               {
    //                   "moonrise_ts": 1625822795,
    //                   "wind_cdir": "SW",
    //                   "rh": 58,
    //                   "pres": 1006.5,
    //                   "high_temp": 34.7,
    //                   "sunset_ts": 1625877203,
    //                   "ozone": 305.5,
    //                   "moon_phase": 0.000721845,
    //                   "wind_gust_spd": 1.81348,
    //                   "snow_depth": 0,
    //                   "clouds": 63,
    //                   "ts": 1625803260,
    //                   "sunrise_ts": 1625825099,
    //                   "app_min_temp": 24.6,
    //                   "wind_spd": 1.10624,
    //                   "pop": 20,
    //                   "wind_cdir_full": "southwest",
    //                   "slp": 1020,
    //                   "moon_phase_lunation": 1,
    //                   "valid_date": "2021-07-09",
    //                   "app_max_temp": 36.4,
    //                   "vis": 24.128,
    //                   "dewpt": 19.4,
    //                   "snow": 0,
    //                   "uv": 8.43817,
    //                   "weather": {
    //                       "icon": "c03d",
    //                       "code": 803,
    //                       "description": "Broken clouds"
    //                   },
    //                   "wind_dir": 230,
    //                   "max_dhi": null,
    //                   "clouds_hi": 58,
    //                   "precip": 0.0625,
    //                   "low_temp": 23.8,
    //                   "max_temp": 34.7,
    //                   "moonset_ts": 1625877619,
    //                   "datetime": "2021-07-09",
    //                   "temp": 29.4,
    //                   "min_temp": 23.8,
    //                   "clouds_mid": 51,
    //                   "clouds_low": 13
    //               }
    //           ],
    //               "city_name": "Raleigh",
    //                   "lon": "-78.63861",
    //                       "timezone": "America/New_York",
    //                           "lat": "35.7721",
    //                               "country_code": "US",
    //                                   "state_code": "NC"
          
    //   };
        
    // const actual = mungedWeather(input);

    //   const data = await fakeRequest(app)
    //     .get('/weather?latitude=45.5202471&longitude=-122.6741949')
    //     .expect('Content-Type', /json/)
    //     .expect(200);

    //   expect(actual).toEqual(expectation);
    // });
  });
});
